import ButtonLink from '@/components/ButtonLink'
import React from 'react'

export const metadata = {
  title: 'Home - Create Next App',
  description: 'Generated by create next app',
}

const Home = () => {
  return (
    <>
      <h1 className="text-center text-3xl font-bold uppercase">
        Mario Rodriguez    </h1>
      <p className="mb-8 text-center text-gray-700">Fullstack Developer</p>
      <p className="mb-8 text-left">With extensive experience in graphic design, I possess a diverse range of technical skills including JavaScript, ReactJs, HTML 5, CSS 3, Bootstrap, NodeJs, MongoDB, ExpressJs, and Handlebars. I have successfully completed coding projects such as Champ Car World Series, JAM session, and SpliTrip. In addition to my technical expertise, I possess strong soft skills such as effective communication, teamwork, problem-solving, stress management, leadership, and adaptability. Additionally, I am fluent in both Spanish and English </p>

      <p className="mb-8 text-left">
        To further enhance my skills, I completed a Full Stack Web Development course at Ironhack and a QA Manual Tester course at Coderhouse. With a professional background as a Freelance Graphic Web Designer, Backup Supervisor, QA Manual Tester & Web Designer, and Customer Service & Technical Support Advisor, I have gained practical experience in the field.
      </p>

      <p className="mb-8 text-left">
        As a passionate learner, I aspire to become a Senior Full Stack Web Developer and constantly strive to learn and grow in my field.
      </p>

      <div className="text-center">
        <ButtonLink href="/blog">Ir al blog</ButtonLink>
      </div>
    </>
  )
}

export default Home