import { allPosts, Post } from "contentlayer/generated";
import PostList from '@/components/PostList'
import PostPagination from '@/components/PostPagination';
import { getPagination } from "@/utils/pagination";


const posts: Post[] = allPosts.sort((a, b) =>b.date.localeCompare(a.date))

export const metadata = {
    title: "Lista de todos los post",
    description: "Description posts - Generated by create next app",
  };
  
  const Posts = () => {
    const { currentPosts, totalPages } = getPagination(allPosts);
  
    return (
      <div className="grid gap-4">
        <PostList posts={currentPosts} />
        {totalPages > 1 && <PostPagination totalPages={totalPages} />}
      </div>
    );
  };
  export default Posts;